### ISSUE TITLE
Put a few buttons in the menu linked to UITool functions

### ISSUE THREAD

**Issue by patmo141** [patmo141/cut_mesh#104]
Place a buttton in the menu linked to the "find_network_cycles" function (which is currently linked to F3 key)

**Comment by patmo141** [comment]
look at this file

https://github.com/CGCookie/retopoflow/blob/master/rfmode/rfcontext_ui.py

**Comment by patmo141** [comment]
and then here is an example of adding buttons check out these lines https://github.com/CGCookie/retopoflow/blob/11f80fb4102d45eac95888f971c3627928e5ec13/rfmode/rftool_contours.py#L87

**Comment by ooMICAHoo** [comment]
Completed. I also added some instructions.

**Comment by ooMICAHoo** [comment]
So I added a button for Find Network Cycles. I also added a list of instructions that changes dynamically depending on what state the user is in.
