### ISSUE TITLE
Do not runs even in Linux and Windows

### ISSUE THREAD

**Issue by cogitas3d** [patmo141/cut_mesh#15]
Dear Patmo141,

I'm trying do to Cut-Mesh works on Blender more than a year but I was not able. I test in Ubuntu and Windows, in a lot of versions, but simply doesnt run.

A think that I saw is that in your examples appear a green line when you click on C. In my case appear only some green points... without the cut line.

The message is always the same:

> sketch confirmed
> sketch too short, cant confirm
> 
> 
> BEGIN CUT ON POLYLINE
> first face group index
> (5287, [0])
> final group not added to dictionary yet
> (5302, [13])
> FACE GROUPS
> {5216: [6], 5347: [8], 5287: [0], 5213: [7], 5297: [12], 5275: [11], 5182: [3], 5302: [13], 5273: [10], 5210: [5], 4859: [1], 4860: [2], 5181: [4], 5278: [9]}
> m, IND
> (0, 0)
> m, IND
> (1, 1)
> prev face prevented walking in the Verts0 direction
> m, IND
> (2, 2)
> m, IND
> (3, 3)
> m, IND
> (4, 4)
> m, IND
> (5, 5)
> prev face prevented walking in the Verts1 direction
> m, IND
> (6, 6)
> m, IND
> (7, 7)
> m, IND
> (8, 8)
> m, IND
> (9, 9)
> m, IND
> (10, 10)
> m, IND
> (11, 11)
> m, IND
> (12, 12)
> m, IND
> (13, 13)
> prev face prevented walking in the Verts0 direction
> This is the loop closing segment.  2
> left click modal inner
> face selected!!
> seed set

Can you tell something about this? I guess I'm doing something wrong, but I'm following the video and text you share on Youtube and GutHub.

Thank you for the attention!

**Comment by aalavandhaann** [comment]
Hello Cogitas,

Can you tell us what is the Blender version you are using? Did you press the right shortcut keys? Also did you try using the API directly to verify this?

Regards,

#0K

**Comment by cogitas3d** [comment]
I tryied in 2.72 until 2.77, the last attempt.

I'm using this guide:

> Drawing the cut Outline -LeftClick to start polyline outline -LeftClick to extend polyline -LeftClick first point to close the loop
> 
> -RightClick any point to delete, or 'X' to delete selected point
> 
> Editing the Outline -LeftClick any point to select it -'G' to grab and move the selected point -'X' to delete the selected point -'Right Click' to delete any point
> 
> Preivew the cut, and verify it -'C' to preview the cut -Invalid segments will be drawn in red -Valid segments will be drawn in green -Cut it ready when all segments are green -Move the invalid points, add or delete poitns untial total outline is green
> 
> Select the part of mesh to be removed -'S' and the LeftClick inside or outside of the loop. Yellow points will appear where the click was placed.
> 
> 'D' to calculate the intermediate step behind the scenes
> 
> 'E' to cut and separate the mesh and finish operator.

About the API, I dont know what you're talkink about. I'm not a developer, sorry.

Thank you

**Comment by aalavandhaann** [comment]
Oh sorry about that. I didn't know if you were a developer or not. No worries. Even I had trouble running it on Blender but after some queries to Patmo, I came to know that it should work with 2.76 without any trouble. Did you try 2.76? 

Also please do us a favor. Try running Blender from Terminal (You were saying about using Ubuntu). Then try doing the actions like before. Let us know what you see in the terminal window. Okay?

Regards,

#0K

**Comment by cogitas3d** [comment]
Thank you aaiavandhaann

The terminal show this:

~/Programs/blender-2.76-linux-glibc211-x86_64$ ./blender
connect failed: No such file or directory
Read new prefs: /home/cogitas3d/.config/blender/2.76/config/userpref.blend
found bundled python: /home/cogitas3d/Programs/blender-2.76-linux-glibc211-x86_64/2.76/python
read blend: /home/cogitas3d/del/untitled.blend
sketch confirmed
sketch too short, cant confirm


BEGIN CUT ON POLYLINE
first face group index
(21111, [0])
final group not added to dictionary yet
(20862, [17])
FACE GROUPS
{20993: [14], 21000: [13], 20843: [2], 21132: [1], 20749: [6], 20751: [7], 19953: [10], 20723: [5], 19988: [9], 20862: [17], 20727: [4], 21017: [15], 19866: [12], 20847: [3], 19964: [11], 21111: [0], 19998: [8], 20863: [16]}
m, IND
(0, 0)
m, IND
(1, 1)
m, IND
(2, 2)
m, IND
(3, 3)
prev face prevented walking in the Verts1 direction
m, IND
(4, 4)
m, IND
(5, 5)
prev face prevented walking in the Verts0 direction
m, IND
(6, 6)
m, IND
(7, 7)
m, IND
(8, 8)
m, IND
(9, 9)
m, IND
(10, 10)
There are 3 crossed edges
There are 4 total edges
signed_ds
[0.03084156126715243, 0.03100958827417344, 0.0]
m, IND
(11, 11)
m, IND
(12, 12)
m, IND
(13, 13)
m, IND
(14, 14)
m, IND
(15, 15)
m, IND
(16, 16)
m, IND
(17, 17)
prev face prevented walking in the Verts1 direction
This is the loop closing segment.  2
left click modal inner
face selected!!
seed set

**Comment by aalavandhaann** [comment]
Looks to be fine. Did you get these output after pressing the 'E' key? If the action doesn't work I usually see some errors in the terminal like this

`File "/home/ashok/.config/blender/2.76/scripts/addons/cut_mesh/modaloperator.py", line 109, in draw_callback_postview
    self.draw_postview(context)
  File "/opt/blender/2.76/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polytrim has been removed
Traceback (most recent call last):
  File "/home/ashok/.config/blender/2.76/scripts/addons/cut_mesh/modaloperator.py", line 114, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "/opt/blender/2.76/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polytrim has been removed
Traceback (most recent call last):
  File "/home/ashok/.config/blender/2.76/scripts/addons/cut_mesh/modaloperator.py", line 109, in draw_callback_postview
    self.draw_postview(context)
  File "/opt/blender/2.76/scripts/modules/bpy_types.py", line 590, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polytrim has been removed
Traceback (most recent call last):
`

Also use the code tag if you want to paste some output from Terminal etc.,, One more thing, are you using the Polytrim tool invoked from the spacebar? I am sure you are following the steps as mentioned in the homepage but just wanted to be sure.

Regards,

#0K

**Comment by patmo141** [comment]
Hi Cicero,

Can I see a screen shot of the model you are using, and if you can upload a .blend file for me to test that would be great.  The terminal output looks like it is working.

Sincerely,
Patrick

**Comment by cogitas3d** [comment]
Thank you for the attention

aalavandhaann I pressed E after and nothing appear on terminal. The output was the same above.

patmo141 I upload the test file here: www.ciceromoraes.com.br/downloads/cut.blend

A big hug!

**Comment by patmo141** [comment]
Ok, when I test on suzanne, I do get some odd behavior.  Go into Edit Mode after you Draw Cut, S + seed, C, D, E.  Go into edge select mode. Then select non manifold and you if there are edges on your cut that are not selected, they need to be split.  I am unsure how an edge that is created with my cuts is not also split for splitting the piece you want out.  This seems to happen less if the model is triangulated.  I will make a new bug!

https://youtu.be/L9gYO9Eni6g

**Comment by cogitas3d** [comment]
Great patmo141!

It is already perfect to me! Now I'll work better in our project with photogrammetry+3D printing (or Ct-Scan) to creat prosthetics like this:

http://www.dailymail.co.uk/sciencetech/article-3678651/Animal-avengers-rescue-Adorable-puppy-eat-3D-printed-tooth-replaces-one-broke-chewing.html#comments-3678651

And work with orthognatic planning surgery.

Thank you very much!
