### ISSUE TITLE
Error when cutting non manifold

### ISSUE THREAD

**Issue by patmo141** [patmo141/cut_mesh#20]
![image](https://cloud.githubusercontent.com/assets/2917743/16750598/e8d216c2-47a0-11e6-93c1-ed3794a2ef62.png)

**Comment by patmo141** [comment]
appears if distances are equal, then it tries to order the actual edges which is impossible

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/16750668/5bdc1870-47a1-11e6-8ec9-a8419fa87cd3.png)

**Comment by patmo141** [comment]
still happening

![image](https://cloud.githubusercontent.com/assets/2917743/22606392/cadd5fa4-ea21-11e6-9c02-b8a90541b3be.png)

**Comment by ooMICAHoo** [comment]
Should be fixed! I fixed it when I worked on issue #35, which was the same issue
