### ISSUE TITLE
Error when hole filling

### ISSUE THREAD

**Issue by Guisan** [patmo141/cut_mesh#21]
Sometimes this happens.
![screenshot 116](https://cloud.githubusercontent.com/assets/17667365/17035210/5cdfa9fc-4f86-11e6-95a4-47cadccacbc7.png)
Guido

**Comment by Guisan** [comment]
![screenshot 117](https://cloud.githubusercontent.com/assets/17667365/17038182/baf61662-4f94-11e6-9d41-afbafc02207b.png)

**Comment by patmo141** [comment]
I can confirm both of these

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/17077694/4bd2c38e-50a7-11e6-9747-f82a29e252fc.png)

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/17099817/aab16648-5238-11e6-8780-7123bdf7bb0a.png)

new highly improved results with new algorithm from this paper
http://www.cad.zju.edu.cn/home/hwlin/pdf_files/A-robust-hole-filling-algorithm-for-triangular-mesh.pdf

**Comment by Guisan** [comment]
I've read the paper and the result I can see in the picture above is great! The surface can be finished with Sculpt Mode (Dyntopo).

**Comment by patmo141** [comment]
closed in bd76f185ee86bd156d62d657b21c5e9fc6def0a5
