### ISSUE TITLE
Polytrim is not working

### ISSUE THREAD

**Issue by arelaxend** [patmo141/cut_mesh#26]
Hi,

The tool looks great. I am currently doing exactly what's in your youtube video and the last step "press E" to do the final cut is not working. It does not create a separate mesh with the cut portion inside.

I added the blend file.

What do you think ? Thank you.
Alexandre

[polytrim_test.stl.zip](https://github.com/patmo141/cut_mesh/files/417224/polytrim_test.stl.zip)

**Comment by patmo141** [comment]
Thank you for the report and for posting a .zip.  Can you please post a screen shot of the cut you are attempting to make so I can simulate what you are doing.

**Comment by patmo141** [comment]
Also, I have updated the hotkeys recently to mimic Blender's mesh functions so 'E' actually just adds the new edges into the mesh, without splitting them. I need to switch that to 'K' for knife.   The addon now uses 'Shift + D', 'X', 'P', and 'Y' (which follow blenders default keymap to duplicated, delete, separate and split respectively.  I have just updated the wiki as well.

**Comment by patmo141** [comment]
I tested your mesh, it seems to work fine.  I think you have just been a victim of my not updating the documentation fast enough.  I have updated keymap so the 'K' just cuts the mesh like in blender editmode without splitting edges and 'E' will no longer do anything.  I will close this issue when I hear back from you that it works.

![image](https://cloud.githubusercontent.com/assets/2917743/17651798/bb3f3568-623b-11e6-861b-cbf04d197449.png)

**Comment by patmo141** [comment]
I have updated the wiki to match
https://github.com/patmo141/cut_mesh/wiki/Basic-Usage

**Comment by arelaxend** [comment]
Thank you patmo141. 

I started "polytrim" function. Then selected points on the mesh, then press C, S, D.
<img width="613" alt="capture d ecran 2016-08-14 a 22 22 12" src="https://cloud.githubusercontent.com/assets/8854658/17651796/fd355e34-626d-11e6-99bd-efa1e92bda43.png">

When press Y, it create a new mesh with the selection I made..
<img width="569" alt="capture d ecran 2016-08-14 a 22 23 15" src="https://cloud.githubusercontent.com/assets/8854658/17651795/fd077d0c-626d-11e6-9d68-ee6413d80a3c.png">

In that mesh, the tooth is not contained. In your picture, it is working as I can see (purple color). What else did you do to obtain the result ? Thank you

Question 2: When I do polytrim, I cannot play with the view (like to rotate the view around my object and so on..). It is then difficult to do the selection. It is like polytrim is blocking these functionnalies. Is that correct ?

**Comment by patmo141** [comment]
Re Navigation/View:  Yes, the addon blocks all user input and intercepts it, however it looks for the default Blender navigation keys and passes those through. Are you using a different key map such as Maya or 3ds style navigtion?

Re Line Mesh:  Yes, the user drawn cut is always produced as a separate line mesh, this is for testing and verification purposes.

Re No New Mesh: 
-K, Y, are doing something, however it will not be obvious until you go into editmode and on a dense mesh, it may not be obvious.
-Try 'P' or 'Shift + D'  These will make a new object
-'X' will delete the part leaving a hole in the original object.

I added a new color to the object manually, but I can make the tool add a random color to the new object to give feedback to the user

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/17652137/26a3012a-6243-11e6-867a-8cfc02d9fa90.png)

I have added function to autimatically add a new material to the new object in the scene when using the 'Shift + D' or 'P' functions.

**Comment by arelaxend** [comment]
Great, it perfectly worked. Thank you. I start to really like Blender right now and especially your tool. 👍 I think this is a great feature to have a new material when using "Shift + D" or "P".

Re Navigation/View: The "Numpad 1" etc. shorcuts are not working also. I use the default Blender settings. What do you mean when you say "it looks for the default Blender navigation keys and passes those through" ?

**Comment by patmo141** [comment]
https://github.com/patmo141/cut_mesh/blob/b4e74dbdef20200a7497234022b863adb40875a6/modaloperator.py#L62

middle mouse, scroll wheel allow for panning and zooming the view.  I will upgrade to more comprehensive navigation handling.  For that let's create a new issue.
