### ISSUE TITLE
Error while removing vertexes in polytrim

### ISSUE THREAD

**Issue by arelaxend** [patmo141/cut_mesh#28]
Hello,

I encountered an error while removing vertexes. This error stops the "polytrim" function.

<img width="1440" alt="capture d ecran 2016-08-15 a 17 10 41" src="https://cloud.githubusercontent.com/assets/8854658/17675873/fe6b6e38-632b-11e6-835d-9984c4b0ac18.png">

What do you think ? Thank you. Alexandre

**Comment by patmo141** [comment]
Is it the last one you remove?

**Comment by arelaxend** [comment]
Yes.
