### ISSUE TITLE
Error while running "triangle fill Hole"

### ISSUE THREAD

**Issue by arelaxend** [patmo141/cut_mesh#29]
Hi,

I encountered this error while running the "triangle fill hole" function on a mesh which contains the following hole:

Resolution: 0.03
Smooth iteration: 20
Max iteration: 10000

<img width="1440" alt="capture d ecran 2016-08-15 a 17 30 27" src="https://cloud.githubusercontent.com/assets/8854658/17675900/21fdf280-632c-11e6-9d2c-beae983c5aba.png">
<img width="1440" alt="capture d ecran 2016-08-15 a 17 28 39" src="https://cloud.githubusercontent.com/assets/8854658/17675899/21fc5c5e-632c-11e6-8bd0-ed50ca1353cb.png">

What do you think ? Thank you.

Alexandre

**Comment by patmo141** [comment]
1.  Can you post the .blend file
2.  Can you open the system console printout?

**Comment by patmo141** [comment]
I think the problem is that you have too many vertices selected.  You need to only have the hole selected.  Like this.

![image](https://cloud.githubusercontent.com/assets/2917743/17686048/2d8ed2f8-6337-11e6-83d1-376bc0549739.png)

**Comment by arelaxend** [comment]
You are absolutely right! It works perfectly.
