### ISSUE TITLE
No green circle on hover Polytrim vertice.

### ISSUE THREAD

**Issue by Vovochka777** [patmo141/cut_mesh#32]
Only 10% of vertices become green. I can't close loop. 

![screenshot_1](https://cloud.githubusercontent.com/assets/1706701/23415709/c061f8ca-fde8-11e6-9766-41c0355b6d49.jpg)

**Comment by patmo141** [comment]
can you post the screen shot again. It doesn't seem to load.

**Comment by Vovochka777** [comment]
http://ortho.studio/polytrim.avi

**Comment by patmo141** [comment]
I see.  Can you upload  (or email me if you need to keep the file private) the .stl of the mesh or the .blend file.

patrick dot moore dot bu at gmail

**Comment by patmo141** [comment]
Ok, I think I know what it is.  I may have forgotten to include object transform matrix in raycastiNG result.
