### ISSUE TITLE
Error when attempting to enable add-on

### ISSUE THREAD

**Issue by eddddddddd** [patmo141/cut_mesh#34]
Hi, thanks for sharing this. Looks like a great tool.
When I try to enable the add-on I get the following error:

![screenshot from 2017-11-16 16-51-53](https://user-images.githubusercontent.com/33729041/32904916-698d5442-caf0-11e7-9e8e-c4c93c534c93.png)

**Comment by aalavandhaann** [comment]
Dear edddddd,

You need to have the numpy module installed on your Blender python environment. Can you please let us know the ecosystem of the blender you were testing on? (viz., OS, Blender version etc.,)

Regards,

#0K

**Comment by aalavandhaann** [comment]
Dear edddddd,

You need to have the numpy module installed on your Blender python environment. Can you please let us know the ecosystem of the blender you were testing on? (viz., OS, Blender version etc.,)

Regards,

#0K

**Comment by ooMICAHoo** [comment]
I am going to close this issue as it seems to have been solved. Send me a message if you reject 😄
