### ISSUE TITLE
Ctrl + Leftclick to create separate Input Point

### ISSUE THREAD

**Issue by patmo141** [patmo141/cut_mesh#86]
Currently all new input points search for the closest endpoint to connect to.  If there are no free endpoints, then a lonely point is created.  Ctrl + Leftclick should always create a lonely point.

**Comment by ooMICAHoo** [comment]
Got it working, but the extension preview line needs to disappear when the user holds 'ctrl' so that they can see visually that the point they are adding is not connecting to an endpoint.

**Comment by ooMICAHoo** [comment]
done.
