### ISSUE TITLE
Polytrim doens't works

### ISSUE THREAD

**Issue by cogitas3d** [patmo141/cut_mesh#9]
Dear patmo141,

First of all, congratz for your tools. These are great!

Second, I'm with a problem about Polytrim. I follow the videos and the tutorial on GitHub, but the addon simply doesnt works.

I have this output on terminal:

sketch confirmed
sketch too short, cant confirm
left click modal inner
face selected!!
seed set

But nothing happens at mesh.

May I did somthing wrong?

Thank you and a big hug!

**Comment by patmo141** [comment]
well, it's not working for me either.  I have no idea what's going on at this point ha ha.  I am working on it though

**Comment by patmo141** [comment]
Try now, I've made a few improvements!

**Comment by cogitas3d** [comment]
Hi @patmo141 !

Thank you to share! But unfortunately it doesn't works yet.

I tried at Blender 2.74, 2.76 and 2.77.

All appear be good at 2.76, but doesn't cut anything.

A big hug!

**Comment by patmo141** [comment]
Please upload a blend file

**Comment by Guisan** [comment]
Hi patrick!
I've tested polytrim to cut a big stl file and it work great!
Guido

**Comment by patmo141** [comment]
Excellent!  It still has some failures but we will post new bugs/issues for those.  Thanks
