### ISSUE TITLE
Non Manifold Snap Visualization

### ISSUE THREAD

**Issue by patmo141** [patmo141/cut_mesh#90]
When drawing on the edge of a mesh it puts a little green dot under the cursor.  It's really hard to see.

I would not mind the CirclShader but having it occluded by the mesh, so that basically the circle is only shown "off the edge" of the mesh"

**Comment by patmo141** [comment]
How it is now

![image](https://user-images.githubusercontent.com/2917743/44240606-01f38f80-a18d-11e8-9847-ad1c09ddb867.png)

**Comment by ooMICAHoo** [comment]
I have the circle shader working on non_man snap locations, but I don't quite know where to begin with having it be occluded. Do you have any pointers?

**Comment by ooMICAHoo** [comment]
I fixed this issue, but the circle is not occluded. I will probably need some help figuring this part out.
