### ISSUE TITLE
Get sketching to work again

### ISSUE THREAD

**Issue by ooMICAHoo** [patmo141/cut_mesh#92]

**Comment by patmo141** [comment]
For simple stroke generation, connecting to the endpoints

a)  create an InputPoint for every desired stroke point, append to InputPointMap.points
b) connect all the stroke input points with InputSegments ->  InputSegment(ip0, ip1)
    append to InputPointMap.segments
c) Connect tip and tail stroke InputPoitns to what was "snapped" at start and finish of stroke.

**Comment by ooMICAHoo** [comment]
@patmo141 A thought I had: Make sketch points distance from each other equal. the distance could be variable depending on how long the user sketches (holds down leftclick)
